Repository tinkoff-ai/etna, pull requests merged in 2021-11, with the labels that each got.

#240 Add possibility to set custom `in_column` for `ConfidenceIntervalOutliersTransform`
  CHANGELOG.md
  etna/analysis/outliers/confidence_interval_outliers.py
  etna/loggers/wandb_logger.py
  etna/transforms/outliers.py
  tests/test_analysis/test_outliers/test_confidence_interval_outliers.py
  tests/test_transforms/test_outliers_transform.py
Labels: enhancement

#234 Fix typing in Pipeline
  etna/datasets/tsdataset.py
  etna/ensembles/voting_ensemble.py
  etna/pipeline/autoregressive_pipeline.py
  etna/pipeline/pipeline.py
Labels: documentation

#242 Add note about parameter n_subsampes to TheilSenTrendTransform
  etna/transforms/detrend.py
Labels: enhancement

#245 Fix default value for `TSDataset.tail`
  CHANGELOG.md
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
Labels: bug

#247 Make `in_column` the first argument in every transform
  CHANGELOG.md
  etna/transforms/add_constant.py
  etna/transforms/lags.py
  etna/transforms/scalers.py
  etna/transforms/sklearn.py
  etna/transforms/statistics.py
  tests/test_transforms/test_lag_transform.py
Labels: enhancement

#241 Create method `TSDataset.flatten`
  CHANGELOG.md
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
Labels: enhancement

#246 New workflow to run notebooks after merging
  .github/workflows/notebooks.yml
  .github/workflows/test.yml
  scripts/notebook_runner.py
Labels: enhancement

#244 Fix processing empty exog values
  CHANGELOG.md
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
Labels: bug

#248 Update mypy checking and fix issues with it
  CHANGELOG.md
  Makefile
  etna/clustering/distances/base.py
  etna/clustering/distances/distance_matrix.py
  etna/clustering/distances/dtw_distance.py
  etna/clustering/distances/euclidean_distance.py
  etna/clustering/hierarchical/base.py
  etna/clustering/hierarchical/dtw_clustering.py
  etna/clustering/hierarchical/euclidean_clustering.py
  etna/commands/backtest_command.py
  etna/commands/forecast_command.py
  etna/ensembles/stacking_ensemble.py
  etna/ensembles/voting_ensemble.py
  etna/loggers/wandb_logger.py
  etna/metrics/base.py
  etna/metrics/functional_metrics.py
  etna/metrics/utils.py
  etna/model_selection/backtest.py
  etna/models/base.py
  etna/models/prophet.py
  etna/pipeline/autoregressive_pipeline.py
  etna/pipeline/base.py
  etna/pipeline/pipeline.py
  examples/clustering.ipynb
  mypy.ini
  poetry.lock
  pyproject.toml
  tests/test_ensembles/test_stacking_ensemble.py
  tests/test_ensembles/test_voting_ensemble.py
  tests/test_pipeline/test_autoregressive_pipeline.py
  tests/test_pipeline/test_pipeline.py
Labels: bug

#254 Fix issue with `aggregate_metics=True` for `ConsoleLogger` and `WandbLogger`
  CHANGELOG.md
  etna/loggers/console_logger.py
  etna/loggers/wandb_logger.py
Labels: bug

#257 Update binder requirements
  .binder/requirements.txt
  CHANGELOG.md
Labels: bug

#252 Update outliers notebook
  CHANGELOG.md
  docs/source/tutorials.rst
  etna/analysis/outliers/hist_outliers.py
  examples/README.md
  examples/outliers.ipynb
Labels: notebook

#250 Add to_numeric conversion in SkleanModel
  CHANGELOG.md
  etna/models/sklearn.py
  tests/test_models/test_linear_model.py
Labels: bug

#264 Replace cycle over segments with vectorized expression in `TSDataset._check_endings`
  CHANGELOG.md
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
Labels: enhancement

#261 Add get_model_relevance_table
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/feature_relevance/__init__.py
  etna/analysis/feature_relevance/relevance.py
  etna/analysis/feature_relevance/relevance_table.py
  tests/conftest.py
  tests/test_analysis/test_feature_relevance/test_relevance.py
  tests/test_analysis/test_feature_relevance/test_relevance_table.py
  tests/test_analysis/test_feature_relevance/test_statistics_relevance_table.py
Labels: enhancement

#265 MeanSegmentEncoderTransform
  CHANGELOG.md
  etna/transforms/__init__.py
  etna/transforms/segment_encoder.py
  tests/test_transforms/test_segment_encoder_transform.py
Labels: enhancement

#274 Delete restriction on version of pandas
  poetry.lock
  pyproject.toml
Labels: enhancement

#268 add ranks
  CHANGELOG.md
  etna/analysis/feature_relevance/relevance.py
  tests/test_analysis/test_feature_relevance/test_relevance.py
Labels: enhancement

#285 Rename confidence interval to prediction interval, start working with quantiles instead of interval_width
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/outliers/__init__.py
  etna/analysis/outliers/prediction_interval_outliers.py
  etna/ensembles/stacking_ensemble.py
  etna/ensembles/voting_ensemble.py
  etna/models/base.py
  etna/models/prophet.py
  etna/models/sarimax.py
  etna/pipeline/autoregressive_pipeline.py
  etna/pipeline/base.py
  etna/pipeline/pipeline.py
  etna/transforms/__init__.py
  etna/transforms/outliers.py
  examples/README.md
  examples/outliers.ipynb
  tests/test_analysis/test_outliers/test_confidence_interval_outliers.py
  tests/test_ensembles/test_stacking_ensemble.py
  tests/test_ensembles/test_voting_ensemble.py
  tests/test_models/test_prophet.py
  tests/test_models/test_sarimax_model.py
  tests/test_pipeline/conftest.py
  tests/test_pipeline/test_autoregressive_pipeline.py
  tests/test_pipeline/test_pipeline.py
  tests/test_transforms/test_outliers_transform.py
Labels: enhancement

#277 Add `FilterFeaturesTransform`
  CHANGELOG.md
  etna/transforms/__init__.py
  etna/transforms/filter.py
  tests/test_transforms/test_filter_transform.py
Labels: enhancement

#219 Update README.md
  README.md
Labels: documentation

#296 ResampleWithDistributionTransform
  CHANGELOG.md
  etna/transforms/__init__.py
  etna/transforms/resample.py
  tests/test_transforms/test_resample_transform.py
Labels: enhancement

#305 Add `duplicate_data`
  CHANGELOG.md
  etna/datasets/__init__.py
  etna/datasets/utils.py
  tests/test_datasets/test_utils.py
Labels: enhancement

#306 Add `FourierTransform`
  CHANGELOG.md
  etna/transforms/__init__.py
  etna/transforms/fourier.py
  tests/test_transforms/test_fourier_transform.py
Labels: enhancement
