Repository tinkoff-ai/etna, pull requests merged in 2021-12, with the labels that each got.

#333 Inference vectorization for regression models
  CHANGELOG.md
  etna/models/catboost.py
  etna/models/sklearn.py
  tests/test_models/test_catboost.py
Labels: enhancement

#350 Fix pickle `DTWClustering`
  CHANGELOG.md
  etna/clustering/distances/dtw_distance.py
  tests/test_clustering/test_clustering.py
Labels: bug

#361 Add FutureMixin and update out_colum generation
  etna/transforms/add_constant.py
  etna/transforms/base.py
  etna/transforms/datetime_flags.py
  etna/transforms/fourier.py
  etna/transforms/lags.py
  etna/transforms/resample.py
  etna/transforms/segment_encoder.py
  etna/transforms/special_days.py
  etna/transforms/statistics.py
  etna/transforms/trend.py
  tests/test_transforms/test_dateflags_transform.py
  tests/test_transforms/test_fourier_transform.py
  tests/test_transforms/test_lag_transform.py
  tests/test_transforms/test_timeflags_transform.py
  tests/test_transforms/test_trend_transform.py
Labels: enhancement

#372 Add S3FileLogger and LocalFileLogger
  CHANGELOG.md
  etna/loggers/__init__.py
  etna/loggers/base.py
  etna/loggers/console_logger.py
  etna/loggers/file_logger.py
  etna/loggers/wandb_logger.py
  poetry.lock
  pyproject.toml
  tests/test_loggers/test_file_logger.py
Labels: enhancement

#381 Set mypy strict_optional = True
  CHANGELOG.md
  etna/clustering/distances/distance_matrix.py
  etna/clustering/hierarchical/base.py
  etna/ensembles/stacking_ensemble.py
  etna/loggers/file_logger.py
  etna/metrics/base.py
  etna/models/nn/deepar.py
  etna/models/nn/tft.py
  etna/models/sarimax.py
  etna/pipeline/autoregressive_pipeline.py
  etna/pipeline/pipeline.py
  etna/transforms/change_points_trend.py
  etna/transforms/detrend.py
  etna/transforms/filter.py
  etna/transforms/gale_shapley.py
  etna/transforms/outliers.py
  etna/transforms/resample.py
  etna/transforms/sklearn.py
  etna/transforms/special_days.py
  etna/transforms/statistics.py
  etna/transforms/stl.py
  mypy.ini
  tests/test_clustering/test_clustering.py
  tests/test_clustering/test_distance_matrix.py
  tests/test_ensembles/test_stacking_ensemble.py
  tests/test_models/nn/test_deepar.py
  tests/test_models/nn/test_tft.py
  tests/test_models/test_sarimax_model.py
  tests/test_pipeline/test_autoregressive_pipeline.py
  tests/test_pipeline/test_pipeline.py
  tests/test_transforms/test_change_points_trend_transform.py
  tests/test_transforms/test_outliers_transform.py
  tests/test_transforms/test_special_days_transform.py
  tests/test_transforms/test_stl_transform.py
Labels: enhancement

#383 Change the way ProphetModel works with regressors
  etna/models/prophet.py
  tests/test_models/test_prophet.py
Labels: enhancement

#405 Fix docstring for `TimeFlagsTransform`
  etna/transforms/datetime_flags.py
Labels: documentation

#402 Add comment about `WindowStatisticsTransform` with `window=-1`
  etna/transforms/statistics.py
Labels: documentation

#408 Add parameter changepoint_prior_scale to Prophet
  CHANGELOG.md
  etna/models/prophet.py
Labels: enhancement

#413 Moving `_check_endings` call to `make_future`
  CHANGELOG.md
  etna/datasets/tsdataset.py
  tests/conftest.py
  tests/test_datasets/test_dataset.py
  tests/test_transforms/sklearn/test_power_transform.py
  tests/test_transforms/sklearn/test_scalers_transform.py
  tests/test_transforms/test_add_constant_transform.py
  tests/test_transforms/test_binseg_trend_transform.py
  tests/test_transforms/test_change_points_trend_transform.py
  tests/test_transforms/test_detrend_transform.py
  tests/test_transforms/test_feature_importance_transform.py
  tests/test_transforms/test_gale_shapley.py
  tests/test_transforms/test_impute_transform.py
  tests/test_transforms/test_lag_transform.py
  tests/test_transforms/test_log_transform.py
  tests/test_transforms/test_outliers_transform.py
  tests/test_transforms/test_resample_transform.py
  tests/test_transforms/test_segment_encoder_transform.py
  tests/test_transforms/test_special_days_transform.py
  tests/test_transforms/test_statistics_transform.py
  tests/test_transforms/test_stl_transform.py
  tests/test_transforms/test_trend_transform.py
Labels: enhancement

#409 Change method `TSDataset.describe`
  CHANGELOG.md
  etna/datasets/tsdataset.py
  examples/get_started.ipynb
  tests/test_datasets/test_dataset.py
Labels: enhancement

#374 Add regressors updating in transform loops
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
  tests/test_transforms/test_trend_transform.py
Labels: enhancement

#421 Refactor transforms that generate many columns
  CHANGELOG.md
  etna/transforms/datetime_flags.py
  etna/transforms/fourier.py
  etna/transforms/lags.py
  examples/custom_transform_and_model.ipynb
  tests/test_transforms/test_dateflags_transform.py
  tests/test_transforms/test_fourier_transform.py
  tests/test_transforms/test_lag_transform.py
  tests/test_transforms/test_timeflags_transform.py
Labels: enhancement

#428 Fix type hints for `DateFlagsTransform._get_column_name` and `TimeFlagsTransform._get_column_name`
  etna/transforms/datetime_flags.py
Labels: documentation

#414 Add `DifferencingTransform`
  CHANGELOG.md
  etna/transforms/__init__.py
  etna/transforms/math/__init__.py
  etna/transforms/math/differencing.py
  tests/test_transforms/test_math/test_differencing_transform.py
Labels: enhancement

#427 Clarify the behaviour of `TimeSeriesImputerTransform` in case of all NaN values
  CHANGELOG.md
  etna/transforms/missing_values/imputation.py
  tests/test_transforms/test_missing_values/conftest.py
  tests/test_transforms/test_missing_values/test_impute_transform.py
Labels: enhancement
