Repository tinkoff-ai/etna, pull requests merged in 2021-10, with the labels that each got.

#115 Add Pipeline example
  CHANGELOG.md
  README.md
  examples/get_started.ipynb
  poetry.lock
Labels: notebook

#112 Add note about forecast to documentation of models
  CHANGELOG.md
  docs/source/models.rst
Labels: documentation

#82 Add regressors property to `TSDataset`
  CHANGELOG.md
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
Labels: enhancement

#126 Add regressor prefix to columns generated by `TimeFlagsTransform`
  CHANGELOG.md
  etna/transforms/datetime_flags.py
  tests/test_transforms/test_timeflags_transform.py
Labels: bug

#110 Etna 797
  CHANGELOG.md
  etna/clustering/__init__.py
  etna/clustering/base.py
  etna/clustering/distances/__init__.py
  etna/clustering/distances/base.py
  etna/clustering/distances/distance_matrix.py
  etna/clustering/distances/dtw_distance.py
  etna/clustering/distances/euclidean_distance.py
  etna/clustering/hierarchical/__init__.py
  etna/clustering/hierarchical/base.py
  etna/clustering/hierarchical/dtw_clustering.py
  etna/clustering/hierarchical/euclidean_clustering.py
  tests/test_clustering/__init__.py
  tests/test_clustering/test_clustering.py
  tests/test_clustering/test_distance_matrix.py
  tests/test_clustering/test_distances.py
Labels: enhancement

#123 Add Outliers notebook
  CHANGELOG.md
  README.md
  etna/analysis/plotters.py
  examples/EDA.ipynb
  examples/backtest.ipynb
  examples/get_started.ipynb
  examples/outliers.ipynb
Labels: notebook

#135 Add `inverse_transform` in `TimeSeriesImputerTransform`
  CHANGELOG.md
  etna/transforms/imputation.py
  tests/test_transforms/test_impute_transform.py
Labels: bug, enhancement

#137 Fix changelog clustering typo
  CHANGELOG.md
Labels: documentation

#143 Add scaling for cbar in correlation_heatmap
  CHANGELOG.md
  etna/analysis/plotters.py
Labels: enhancement

#172 Add confidence intervals to SARIMA
  CHANGELOG.md
  etna/models/sarimax.py
  tests/test_models/test_sarimax_model.py
Labels: enhancement
