Repository tinkoff-ai/etna, pull requests merged in 2021-09, with the labels that each got.

#8 Adding poetry.lock
  poetry.lock
Labels: enhancement

#1 #2 ETNA-756
  etna/core/__init__.py
  etna/core/mixins.py
  etna/metrics/base.py
  etna/model_selection/backtest.py
  etna/models/base.py
  etna/models/catboost.py
  etna/models/moving_average.py
  etna/models/prophet.py
  etna/models/seasonal_ma.py
  etna/transforms/add_constant.py
  etna/transforms/base.py
  etna/transforms/detrend.py
  etna/transforms/imputation.py
  etna/transforms/lags.py
  etna/transforms/log.py
  etna/transforms/special_day_finder.py
  tests/test_metrics/test_metrics.py
  tests/test_model_selection/__init__.py
  tests/test_model_selection/test_backtest.py
  tests/test_models/test_linear_model.py
  tests/test_transforms/test_dateflags.py
  tests/test_transforms/test_lag_transform.py
Labels: enhancement

#15 Add missing dependency GitPython for generating docs
  poetry.lock
  pyproject.toml
Labels: bug

#17 ETNA-772
  etna/transforms/power.py
  etna/transforms/scalers.py
  etna/transforms/sklearn.py
  tests/test_transforms/test_power.py
  tests/test_transforms/test_scalers.py
Labels: enhancement

#18 Fixed link in EDA section
  examples/EDA.ipynb
Labels: bug

#24 Add check that all segments end at the same timestamp
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
Labels: enhancement

#7 Refactoring of linear trend models
  etna/transforms/detrend.py
  tests/test_transforms/test_detrend_transform.py
Labels: enhancement

#26 Fixed warning problem in `AddConsntTransform` and `LogTransform`
  etna/transforms/add_constant.py
  etna/transforms/log.py
Labels: enhancement

#32 Fix docstring typing issue TimeSeriesCrossValidation
  etna/model_selection/backtest.py
Labels: documentation

#28 ETNA-781: bug fix
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
Labels: bug

#31 ETNA-758: density anomalies threshold -> std
  etna/analysis/outliers/density_outliers.py
  tests/test_analysis/test_outliers/test_density_outliers.py
Labels: enhancement

#35 ETNA-780: regressors don't have enough elements for `make_future`
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
Labels: enhancement

#30 ETNA-759: `MedianOutliersTransform` and `DensityOutliersTransform`
  etna/analysis/outliers/median_outliers.py
  etna/datasets/tsdataset.py
  etna/transforms/__init__.py
  etna/transforms/outliers.py
  tests/test_analysis/__init__.py
  tests/test_transforms/test_outliers_transform.py
Labels: enhancement

#47 Fix failed test `DensityOutliersTransform`
  etna/transforms/outliers.py
  tests/test_transforms/test_outliers_transform.py
Labels: bug

#57 Fully parallel backtest
  etna/model_selection/backtest.py
Labels: enhancement

#52 Absence of return block in `get_anomalies_median`
  etna/analysis/outliers/density_outliers.py
  etna/analysis/outliers/median_outliers.py
Labels: documentation

#53 Transformers missing documentation
  etna/transforms/imputation.py
  etna/transforms/lags.py
  etna/transforms/log.py
  etna/transforms/power.py
  etna/transforms/special_days.py
Labels: documentation

#25 Fix tsdataset getitem method
  etna/datasets/tsdataset.py
  pytest.ini
  tests/test_datasets/test_dataset.py
Labels: bug

#46 ETNA-773: Adding `ConsoleLogger`
  CHANGELOG.md
  etna/datasets/tsdataset.py
  etna/loggers/__init__.py
  etna/loggers/base.py
  etna/loggers/console_logger.py
  etna/model_selection/backtest.py
  etna/models/base.py
  etna/models/catboost.py
  etna/models/nn/deepar.py
  etna/models/nn/tft.py
  etna/models/sklearn.py
  poetry.lock
  pyproject.toml
  tests/test_loggers/__init__.py
  tests/test_loggers/test_console_logger.py
Labels: enhancement

#62 Add cap and floor to prophet regressor columns
  CHANGELOG.md
  etna/models/prophet.py
  tests/test_models/test_prophet.py
Labels: bug

#77 Add Correlation heatmap to EDA
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
Labels: enhancement

#81 Fix `SARIMAXModel` saving init params
  CHANGELOG.md
  etna/models/sarimax.py
Labels: bug

#71 ETNA-774: Adding `WandbLogger`
  CHANGELOG.md
  docs/source/api.rst
  docs/source/index.rst
  docs/source/loggers.rst
  etna/analysis/eda_utils.py
  etna/analysis/outliers/density_outliers.py
  etna/analysis/outliers/median_outliers.py
  etna/analysis/plotters.py
  etna/loggers/__init__.py
  etna/loggers/base.py
  etna/loggers/wandb_logger.py
  etna/metrics/base.py
  etna/model_selection/backtest.py
  etna/models/nn/deepar.py
  etna/models/nn/tft.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#78 Add Pipeline class
  CHANGELOG.md
  etna/pipeline/__init__.py
  etna/pipeline/pipeline.py
  tests/test_pipeline/__init__.py
  tests/test_pipeline/test_pipeline.py
Labels: enhancement

#95 Add interactive plot for anomalies
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#102 More obvious Exception Error for forecasting with unfitted model
  CHANGELOG.md
  etna/models/base.py
  tests/test_models/test_linear_model.py
Labels: bug

#97 Add 'regressor_' prefix to some transforms
  CHANGELOG.md
  etna/transforms/datetime_flags.py
  etna/transforms/lags.py
  etna/transforms/segment_encoder.py
  etna/transforms/special_days.py
  tests/test_model_selection/test_backtest.py
  tests/test_models/nn/test_deepar.py
  tests/test_models/nn/test_tft.py
  tests/test_transforms/test_dateflags_transform.py
  tests/test_transforms/test_lag_transform.py
  tests/test_transforms/test_segment_encoder_transform.py
  tests/test_transforms/test_special_days_transform.py
Labels: enhancement

#101 Add is_weekend column to DateFlagsTransform
  CHANGELOG.md
  etna/transforms/datetime_flags.py
  tests/test_model_selection/test_backtest.py
  tests/test_transforms/test_dateflags_transform.py
Labels: enhancement

#107 Fix bug with hardcoded frequency in `PytorchForecastingTransform`
  CHANGELOG.md
  etna/models/nn/deepar.py
  etna/models/nn/tft.py
  etna/transforms/pytorch_forecasting.py
  tests/test_models/nn/test_deepar.py
  tests/test_models/nn/test_tft.py
  tests/test_transforms/test_pytorch_forecasting_transform.py
Labels: bug, documentation

#114 fix eda notebook
  CHANGELOG.md
  examples/EDA.ipynb
Labels: bug
