Repository tinkoff-ai/etna, pull requests merged in 2022-04, with the labels that each got.

#628 Add `seasonal_plot`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/eda_utils.py
  tests/test_analysis/test_eda_utils.py
Labels: enhancement

#625 Make statistics fast again
  CHANGELOG.md
  etna/transforms/math/statistics.py
  poetry.lock
  pyproject.toml
  tests/test_transforms/test_math/test_statistics_transform.py
Labels: enhancement

#639 Seasonal strategy in TimeSeriesImputerTransform
  CHANGELOG.md
  etna/transforms/missing_values/imputation.py
  tests/test_transforms/test_missing_values/test_impute_transform.py
Labels: enhancement

#643 Add logging to `Metric.__call__`
  CHANGELOG.md
  etna/metrics/base.py
  tests/test_loggers/test_console_logger.py
Labels: enhancement

#647 Attempt to fix bug with exogs in `AutoRegressivePipeline`
  CHANGELOG.md
  etna/pipeline/autoregressive_pipeline.py
  tests/test_pipeline/test_autoregressive_pipeline.py
Labels: bug

#650 Fix MyBinder bug with dependencies
  .binder/requirements.txt
  CHANGELOG.md
Labels: bug

#648 Add instruction about documentation formatting to contribution guide
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation

#651 Fix `custom_transform_and_model` notebook
  CHANGELOG.md
  examples/custom_transform_and_model.ipynb
Labels: documentation

#658 Add Per-segment metric visualization
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
Labels: enhancement

#666 Add `metric_per_segment_distribution_plot`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
Labels: enhancement
