Repository tinkoff-ai/etna, pull requests merged in 2022-02, with the labels that each got.

#475 Make `TSDataset.to_flatten` faster
  CHANGELOG.md
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
Labels: enhancement

#483 Change `np.percentile` to `np.nanpercentile` in loggers.base
  CHANGELOG.md
  etna/loggers/base.py
Labels: enhancement

#503 Remove unnecessary levels from multiindex columns to fix `DifferencingTransform.inverse_transform`
  CHANGELOG.md
  etna/transforms/math/differencing.py
  tests/test_transforms/test_math/test_differencing_transform.py
Labels: bug

#518 Add regressors logic to new transforms
  etna/datasets/tsdataset.py
  etna/transforms/timestamp/holiday.py
  tests/test_datasets/test_dataset.py
  tests/test_transforms/test_encoders/test_categorical_transform.py
  tests/test_transforms/test_timestamp/test_holiday_transform.py
Labels: enhancement

#519 Fix `TSDataset.info`, `TSDataset.describe` methods
  etna/datasets/tsdataset.py
  examples/EDA.ipynb
  examples/get_started.ipynb
  tests/test_datasets/test_dataset.py
Labels: bug, documentation, enhancement

#520 Fix processing `add_noise=True` parameter in datasets generation
  CHANGELOG.md
  etna/datasets/datasets_generation.py
  tests/test_datasets/test_datasets_generation.py
Labels: bug

#521 Add `find_change_points` and tests for it
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/change_points_trend/__init__.py
  etna/analysis/change_points_trend/find_change_points.py
  etna/transforms/decomposition/change_points_trend.py
  tests/test_analysis/test_change_points_trend/test_find_change_points.py
  tests/test_transforms/test_decomposition/test_change_points_trend_transform.py
Labels: enhancement

#530 Add `FitAbstractModel`, `ForecastAbstractModel`, `PredictIntervalAbstractModel`
  etna/models/base.py
Labels: enhancement

#531 Regressors 2.0
  CHANGELOG.md
  etna/datasets/tsdataset.py
  etna/models/prophet.py
  etna/models/sarimax.py
  etna/models/sklearn.py
  etna/transforms/base.py
  etna/transforms/decomposition/trend.py
  etna/transforms/encoders/mean_segment_encoder.py
  etna/transforms/encoders/segment_encoder.py
  etna/transforms/feature_selection/base.py
  etna/transforms/feature_selection/feature_importance.py
  etna/transforms/feature_selection/gale_shapley.py
  etna/transforms/math/add_constant.py
  etna/transforms/math/lags.py
  etna/transforms/missing_values/resample.py
  etna/transforms/timestamp/date_flags.py
  etna/transforms/timestamp/fourier.py
  etna/transforms/timestamp/holiday.py
  etna/transforms/timestamp/special_days.py
  etna/transforms/timestamp/time_flags.py
  examples/EDA.ipynb
  examples/get_started.ipynb
  tests/conftest.py
  tests/test_datasets/test_dataset.py
  tests/test_models/test_catboost.py
  tests/test_models/test_linear_model.py
  tests/test_models/test_prophet.py
  tests/test_models/test_sarimax_model.py
  tests/test_models/test_sklearn.py
  tests/test_transforms/sklearn/test_interface.py
  tests/test_transforms/sklearn/test_power_transform.py
  tests/test_transforms/sklearn/test_scalers_transform.py
  tests/test_transforms/test_decomposition/test_trend_transform.py
  tests/test_transforms/test_encoders/test_categorical_transform.py
  tests/test_transforms/test_feature_selection/conftest.py
  tests/test_transforms/test_feature_selection/test_base_feature_selection_transform.py
  tests/test_transforms/test_feature_selection/test_feature_importance_transform.py
  tests/test_transforms/test_feature_selection/test_gale_shapley_transform.py
  tests/test_transforms/test_missing_values/conftest.py
  tests/test_transforms/test_outliers/test_outliers_transform.py
  tests/test_transforms/test_timestamp/test_fourier_transform.py
  tests/test_transforms/test_timestamp/test_holiday_transform.py
Labels: enhancement

#534 Add `plot_time_series_with_change_points`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
Labels: enhancement

#526 Add installation instruction
  CHANGELOG.md
  README.md
  examples/configs/.etna
Labels: documentation

#536 Update contribution guide
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation

#537 Create PerSegmentBaseModel, PerSegmentPredictionIntervalModel, PerSegmentModel
  etna/models/base.py
  etna/models/prophet.py
  etna/models/sarimax.py
  etna/models/sklearn.py
  tests/test_models/test_linear_model.py
Labels: enhancement

#539 Add `plot_residuals`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
  tests/test_analysis/test_plotters.py
Labels: enhancement

#544 Add table `option` to `ConsoleLogger`
  CHANGELOG.md
  etna/loggers/console_logger.py
  tests/test_loggers/test_console_logger.py
Labels: enhancement

#558 Fix import Literal in plotters
  CHANGELOG.md
  etna/analysis/plotters.py
Labels: bug

#551 Create MultisegmentModel
  CHANGELOG.md
  etna/models/base.py
  etna/models/catboost.py
  etna/models/sklearn.py
Labels: enhancement

#554 Make categorical encoders multisegment
  CHANGELOG.md
  etna/transforms/encoders/categorical.py
  tests/test_transforms/test_encoders/test_categorical_transform.py
Labels: enhancement

#552 Add option `day_number_in_year` to `DateFlagsTransform`
  CHANGELOG.md
  etna/transforms/timestamp/date_flags.py
  examples/custom_transform_and_model.ipynb
  tests/test_transforms/test_timestamp/test_dateflags_transform.py
Labels: enhancement

#567 Add a season feature to `DateFlagsTransform`
  CHANGELOG.md
  etna/transforms/timestamp/date_flags.py
  tests/test_transforms/test_timestamp/test_dateflags_transform.py
Labels: enhancement

#555 Add logging to `TSDataset.make_future`
  CHANGELOG.md
  etna/core/mixins.py
  etna/datasets/tsdataset.py
  tests/test_loggers/test_console_logger.py
Labels: enhancement

#573 Create `AbstractPipeline`
  CHANGELOG.md
  etna/pipeline/base.py
Labels: enhancement
