Repository tinkoff-ai/etna, pull requests merged in 2022-05, with the labels that each got.

#686 Remove parameter `normalize` in linear models
  CHANGELOG.md
  etna/models/linear.py
  tests/test_models/test_linear_model.py
Labels: bug

#685 Fix bugs and documentation for `stl_plot`
  CHANGELOG.md
  etna/analysis/eda_utils.py
Labels: bug, documentation

#691 Fix bugs and documentation for `cross_corr_plot`
  CHANGELOG.md
  etna/analysis/eda_utils.py
  etna/analysis/plotters.py
  etna/analysis/utils.py
  tests/test_analysis/test_eda_utils.py
Labels: bug, documentation

#700 Fix bugs and documentation for `plot_backtest` and `plot_backtest_interactive`
  CHANGELOG.md
  etna/analysis/plotters.py
  tests/test_analysis/test_plotters.py
Labels: bug, documentation

#706 Add `xticks` parameter for `plot_periodogram`, clip frequencies to be >= 1
  CHANGELOG.md
  etna/analysis/plotters.py
Labels: enhancement

#705 Style fixes for EDA methods
  CHANGELOG.md
  etna/analysis/eda_utils.py
  etna/analysis/plotters.py
  etna/analysis/utils.py
  etna/datasets/tsdataset.py
  examples/EDA.ipynb
  examples/NN_examples.ipynb
  examples/assets/readme/get_started.png
  examples/backtest.ipynb
  examples/clustering.ipynb
  examples/custom_transform_and_model.ipynb
  examples/ensembles.ipynb
  examples/exogenous_data.ipynb
  examples/get_started.ipynb
  examples/outliers.ipynb
Labels: documentation, enhancement

#661 Fix warning in FourierTransform
  etna/transforms/timestamp/fourier.py
  tests/test_transforms/test_timestamp/test_fourier_transform.py
Labels: bug
