Repository tinkoff-ai/etna, pull requests merged in 2022-03, with the labels that each got.

#574 Create `EnsembleMixin`
  CHANGELOG.md
  etna/ensembles/__init__.py
  etna/ensembles/base.py
  etna/ensembles/stacking_ensemble.py
  etna/ensembles/voting_ensemble.py
  tests/test_ensembles/test_ensemble_mixin.py
  tests/test_ensembles/test_stacking_ensemble.py
  tests/test_ensembles/test_voting_ensemble.py
Labels: enhancement

#569 Update get_started section in README
  CHANGELOG.md
  README.md
  examples/EDA.ipynb
  examples/NN_examples.ipynb
  examples/assets/readme/get_started.png
  examples/backtest.ipynb
  examples/custom_transform_and_model.ipynb
  examples/data/example_dataset.csv
  examples/get_started.ipynb
  examples/outliers.ipynb
Labels: documentation

#580 Add community section to README.md
  CHANGELOG.md
  README.md
Labels: documentation

#578 Create `BasePipeline`
  CHANGELOG.md
  etna/ensembles/base.py
  etna/ensembles/stacking_ensemble.py
  etna/ensembles/voting_ensemble.py
  etna/models/base.py
  etna/pipeline/autoregressive_pipeline.py
  etna/pipeline/base.py
  etna/pipeline/pipeline.py
  tests/test_ensembles/test_stacking_ensemble.py
  tests/test_ensembles/test_voting_ensemble.py
  tests/test_pipeline/test_autoregressive_pipeline.py
  tests/test_pipeline/test_pipeline.py
Labels: enhancement

#579 Add `plot_features_relevance`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/feature_selection/__init__.py
  etna/analysis/feature_selection/mrmr.py
  etna/analysis/plotters.py
Labels: enhancement

#584 Update `plot_forecast` for multi-forecast mode
  CHANGELOG.md
  etna/analysis/plotters.py
Labels: enhancement

#598 Add `plot_imputation`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
Labels: enhancement

#597 Add `get_residuals`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
  tests/test_analysis/test_plotters.py
Labels: enhancement

#587 Feature Importance as weights in VotingEnsemble
  CHANGELOG.md
  etna/ensembles/voting_ensemble.py
  tests/test_ensembles/test_voting_ensemble.py
Labels: enhancement

#602 Fix that segment is string
  CHANGELOG.md
  etna/analysis/eda_utils.py
  etna/datasets/tsdataset.py
  tests/test_datasets/test_dataset.py
  tests/test_pipeline/conftest.py
Labels: documentation, enhancement

#604 Add `qq_plot`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/eda_utils.py
  etna/analysis/plotters.py
  etna/analysis/utils.py
Labels: enhancement

#608 Fix `get_centroids` returned dataframe columns
  etna/clustering/hierarchical/base.py
Labels: bug

#606 Add `plot_periodogram`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
Labels: enhancement

#610 Add `prediction_actual_scatter_plot`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/eda_utils.py
Labels: enhancement

#615 remove all mutable arguments
  etna/datasets/datasets_generation.py
  etna/ensembles/stacking_ensemble.py
  etna/ensembles/voting_ensemble.py
  etna/models/nn/deepar.py
  etna/models/nn/tft.py
  etna/pipeline/base.py
  etna/pipeline/pipeline.py
Labels: bug

#618 Add `in_column` to `plot_anomalies`, `plot_anomalies_interactive`
  CHANGELOG.md
  etna/analysis/plotters.py
Labels: enhancement

#613 Masked backtest
  CHANGELOG.md
  etna/pipeline/__init__.py
  etna/pipeline/base.py
  tests/test_pipeline/conftest.py
  tests/test_pipeline/test_pipeline.py
Labels: enhancement

#624 Add `plot_holidays`
  CHANGELOG.md
  etna/analysis/__init__.py
  etna/analysis/plotters.py
Labels: enhancement
